# Generated by Django 4.1.3 on 2023-07-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_nuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
