# Generated by Django 4.1.3 on 2023-07-20 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_nuser_delete_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='nuser',
            name='is_staff',
        ),
    ]
